Added an Extra column in the Article table to store the image link to the article
zeeguu/api pull request #128
Opened 2024-03-15 07:59 UTC by tfnribeiro

Added logic so this is retrieved with the article info so it can be displayed in the frontend.

The result can be seen in https://github.com/zeeguu/web/pull/323

2024-03-15 12:59 UTC, mircealungu requested changes
most minor change requests Tiago :)

2024-03-15 12:59 UTC, mircealungu commented on tools/migrations/add_img_url_to_article.sql
> +    UNIQUE INDEX `img_url_id_UNIQUE` (`img_url_id` ASC) VISIBLE;
VISIBLE seems to not be supported by the MySQL engine on the server! if you simply drop it, the query executes.

2024-03-15 12:59 UTC, mircealungu commented on tools/migrations/add_img_url_to_article.sql
> +ALTER TABLE
let's please prefix the name of the migrations with <year>-<month> as in the other examples in the folder.

2024-03-15 17:16 UTC, merged

2024-03-15 17:16 UTC, mircealungu commented
@tfnribeiro  - i've made the two changes I pointed to above myself, because i really want to deploy this today ;) by Monday we should come back to a feed with images :)

2024-03-15 17:29 UTC, tfnribeiro commented
Sounds good! Sorry, I have the Github account on my personal mail and not on the work mail so I didn't get a notification about this.

I wanted to talk about the SQL file names, because technically we could have a PR go through a few changes before being merged, and if we would want to keep track of when it was deployed maybe it would be best to have a run migration scripts that runs a file, and then recreates it with the date?

2024-03-15 17:35 UTC, mircealungu commented
Your observation is very sharp... the reason for the date was in my mind more of a general ordering of the SQL changes than a precise date when the query was run... it's true that it's not very clear why the general ordering si needed ... it just feels nicer somehow? :)

2024-03-15 18:22 UTC, tfnribeiro commented
I was more thinking about if we ever wanted to "rollback" then we would have sort of an idea of the order the changes were made, but I think it's OK. Next time I will put the date in the name :)

2024-03-16 08:14 UTC, mircealungu commented
this is a very good point! 
it would be most useful to keep track of the order of the changes! 
and now I re-read your idea with the running of the migration script and renaming after. 
this is super-cool. I never heard it before! 
you could even run all migrations that don't have a date in alphabetical order and then when you successfully ran one you rename it with the date!

2024-03-18 18:41 UTC, mircealungu commented
Or should we discard articles with path longer than 255? 

These are several examples of articles with long path length: 

￼

There are only two more than 255, the last two above.

If we look at articles that are more than 240 we have a few more: 

/lifeandstyle/ng-interactive/2022/nov/22/christmas-gift-guide-2022-australia-good-gifts-ideas-best-xmas-presents-how-to-shop-for-her-him-by-age-men-them-mum-dad-kids-friends-family-top-unique-thoughtful-useful-online-present-novelty-shopping

/lifeandstyle/ng-interactive/2022/nov/25/christmas-gift-guide-2022-australia-good-gifts-ideas-best-xmas-presents-how-to-shop-for-her-him-by-age-men-them-mum-dad-kids-friends-family-top-unique-thoughtful-useful-online-present-novelty-shopping

/lifeandstyle/ng-interactive/2022/nov/29/christmas-gift-guide-2022-australia-good-gifts-ideas-best-xmas-presents-how-to-shop-for-her-him-by-age-men-them-mum-dad-kids-friends-family-top-unique-thoughtful-useful-online-present-novelty-shopping

/lifeandstyle/ng-interactive/2022/dec/02/christmas-gift-guide-2022-australia-good-gifts-ideas-best-xmas-presents-how-to-shop-for-her-him-by-age-men-them-mum-dad-kids-friends-family-top-unique-thoughtful-useful-online-present-novelty-shopping

/lifeandstyle/ng-interactive/2022/dec/06/christmas-gift-guide-2022-australia-good-gifts-ideas-best-xmas-presents-how-to-shop-for-her-him-by-age-men-them-mum-dad-kids-friends-family-top-unique-thoughtful-useful-online-present-novelty-shopping

/nyheter/innenriks/i/69VRgz/hoeyres-dagligvare-talsperson-lene-westgaard-halle-sier-hun-tror-coop-kan-forsvinne-fra-dagligvaremarkedet-vi-liker-ikke-at-det-bare-er-tre-store-aktoerer-innen-dagligvare-men-det-kan-bli-verre-det-kan-bli-to-sier-hun

/indland/art9407245/L%C3%A6serne-fort%C3%A6ller-om-deres-dybeste-familiehemmeligheder-%C2%BBDa-jeg-kom-hjem-tr%C3%A6ngte-min-mor-mig-op-i-en-krog.-Jeg-sagde-at-hvis-hun-slog-mig-ville-jeg-sl%C3%A5-hende-s%C3%A5-h%C3%A5rdt-jeg-kunne.-S%C3%A5-slog-hun%C2%AB

/politique/macron/ces-inconnus-qui-dirigent-la-france-dominique-boutonnat-et-stephane-sitbon-gomez-soft-power-dominique-boutonnat-le-petit-donateur-de-macron-et-grand-argentier-du-cinema#utm_source=RSS-MARIANNE&utm_medium=Flux-Rss&utm_campaign=RSS_general

/societe/agriculture-et-ruralite/mort-de-la-fille-de-l-agricultrice-decedee-en-ariege-victoire-de-trump-dans-le-new-hampshire-frappes-americaines-en-irak-les-3-infos-de-la-nuit#utm_source=RSS-MARIANNE&utm_medium=Flux-Rss&utm_campaign=RSS_general

/societe/agriculture-et-ruralite/la-fnsea-demande-des-aides-immediates-l-assemblee-favorable-a-une-liberte-garantie-sur-l-ivg-flambee-des-actes-antisemites-les-3-infos-de-la-nuit#utm_source=RSS-MARIANNE&utm_medium=Flux-Rss&utm_campaign=RSS_general

The first few examples here are just shitty SEO titles… we would not lose much by not including them. 

Then again, it wouldn’t be a terrible expense to increase to 512 chars.

Do you see any other perspective that I’m missing? 

Ciao ciao,
M.



> On 18 Mar 2024, at 15.22, Tiago Ribeiro ***@***.***> wrote:
> 
> 
> Suspect Issues
> 
> This pull request was deployed and Sentry observed the following issues:
> 
> ‼️ DataError: (MySQLdb.DataError) (1406, "Data too long for column 'path' at row 1") sqlalchemy.orm.session in _prepare_impl View Issue <https://zeeguu.sentry.io/issues/5079643734/?referrer=github-pr-bot>
> Did you find this useful? React with a 👍 or 👎
> 
> I think this is interesting, I didn't handle long links, but currently path is set to 255, which can maybe be increased if we see this problem too much? Maybe just double it would be enough.
> 
> image.png (view on web) <https://github.com/zeeguu/api/assets/17390076/f763b32e-b99c-45ec-b5e5-ac14a8dd85c7>
> —
> Reply to this email directly, view it on GitHub <https://github.com/zeeguu/api/pull/128#issuecomment-2004052945>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AADRNBZHN53ZADDAOQJTV2DYY32AZAVCNFSM6AAAAABEXQZCESVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBUGA2TEOJUGU>.
> You are receiving this because you modified the open/close state.
>

2024-03-19 15:01 UTC, mircealungu commented
So the simplest thing would be to just drop any article with a too long URL at crawl time?
That would be nice, because it would help us decrease the number of exceptions in Sentry.
And I’d love if we could constantly decrease those till it becomes a special situation that we have exceptions :)

Cheers,
M.

Sent with a Spark
On 19 Mar 2024 at 14.41 +0200, Tiago Ribeiro ***@***.***>, wrote:
> I think I agree, I also think we can just wait to see how often this happens, if it's not so often we can just add a exception catching mechanism to avoid getting errors and we just don't store the URL, maybe that is the best solution :)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>